/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AssistantRole;

import userinterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AssistantOrganization;
import Business.Organization.Organization;
import Business.Organization.WarehouseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssistantMedicineRequest;
import Business.WorkQueue.MedicalDeviceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class AssistantRequestMedicineJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public AssistantRequestMedicineJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        populateComboBox();
        
    }
    private void populateComboBox() {
        medicineAJComboBox.removeAllItems();
        medicineBJComboBox.removeAllItems();
        medicineCJComboBox.removeAllItems();

        int medicineANum = 0;
        int medicineBNum = 0;
        int medicineCNum = 0;
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof WarehouseOrganization){
                medicineANum = ((WarehouseOrganization) organization).getMedicineANum();
                medicineBNum = ((WarehouseOrganization) organization).getMedicineBNum();
                medicineCNum = ((WarehouseOrganization) organization).getMedicineCNum();
            }
                
        }
        
        for(int i = 0;i <= medicineANum;i++)
            medicineAJComboBox.addItem(i+"");
        for(int i = 0;i <= medicineBNum;i++)
            medicineBJComboBox.addItem(i+"");
        for(int i = 0;i <= medicineCNum;i++)
            medicineCJComboBox.addItem(i+"");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestMedicineJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medicineAJComboBox = new javax.swing.JComboBox();
        medicineBJComboBox = new javax.swing.JComboBox();
        medicineCJComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestMedicineJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/WechatIMG16.png"))); // NOI18N
        requestMedicineJButton.setText("Request Medicine");
        requestMedicineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMedicineJButtonActionPerformed(evt);
            }
        });
        add(requestMedicineJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 20));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 89, -1));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/WechatIMG15.png"))); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Assistant Request Medicine");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 30));

        jLabel2.setText("Medicine A");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 20));

        jLabel3.setText("Medicine B");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));

        jLabel4.setText("Medicine C");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 20));

        medicineAJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(medicineAJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        medicineBJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(medicineBJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        medicineCJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(medicineCJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestMedicineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMedicineJButtonActionPerformed
        
        String message = messageJTextField.getText();
        
        AssistantMedicineRequest request = new AssistantMedicineRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        
        //userAccount.getWorkQueue().getWorkRequestList().add(request);
        network.getWorkQueue().getWorkRequestList().add(request);
        System.out.println("Add request success!");
       
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof WarehouseOrganization){
                int currentMedicineANum = ((WarehouseOrganization) organization).getMedicineANum() - Integer.parseInt(medicineAJComboBox.getSelectedItem().toString());
                ((WarehouseOrganization) organization).setMedicineANum(currentMedicineANum);
                
                int currentMedicineBNum = ((WarehouseOrganization) organization).getMedicineBNum() - Integer.parseInt(medicineBJComboBox.getSelectedItem().toString());
                ((WarehouseOrganization) organization).setMedicineBNum(currentMedicineBNum);
                
                int currentMedicineCNum = ((WarehouseOrganization) organization).getMedicineCNum() - Integer.parseInt(medicineCJComboBox.getSelectedItem().toString());
                ((WarehouseOrganization) organization).setMedicineCNum(currentMedicineCNum);
            }
        }
        
        populateComboBox();
    }//GEN-LAST:event_requestMedicineJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AssistantWorkAreaJPanel awjp = (AssistantWorkAreaJPanel) component;
        awjp.populateAppointmentTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox medicineAJComboBox;
    private javax.swing.JComboBox medicineBJComboBox;
    private javax.swing.JComboBox medicineCJComboBox;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestMedicineJButton;
    // End of variables declaration//GEN-END:variables
}
