/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners.ManageFlights.BookCustomerReservation;

import Business.Airplane;
import Business.Customer;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Keyu Liu
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomerReservationJPanel
     */
    private JPanel CardSequenceForFlightJPanel;
    private Airplane airplane;
    private CustomerDirectory customerDirectory;
    
    private int[] col;
    private String[] type;
    
    public ManageCustomerJPanel(JPanel CardSequenceForFlightJPanel, Airplane airplane) {
        initComponents();
        customerDirectory = new CustomerDirectory();
        this.CardSequenceForFlightJPanel = CardSequenceForFlightJPanel;
        this.airplane = airplane;
        this.col = airplane.getAvailableCol();
        this.type = airplane.getAvailableType(1);
        
        
        readCustomerFromCsv();
        
        initialize();
       

    }
    
    private void readCustomerFromCsv(){
        try {
            BufferedReader br=null;
            br = new BufferedReader(new FileReader("src/data/Customers.csv"));
            String line = "";
            
            while ((line = br.readLine()) != null) {
                String[] split=line.split(","); 
                
                Customer c = customerDirectory.addCustomer();
                
                c.setName(split[0]);
                c.setAirplanePicked(split[1]);
                c.setSeatColumn(Integer.valueOf(split[2]));
                c.setSeatType(split[3]);
                c.setSeatRowNum(Integer.valueOf(split[4]));
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void initialize(){
        ComboBoxCol.removeAllItems();
        ComboBoxType.removeAllItems();
        ComboBoxRowNum.removeAllItems();
        txtAirplaneNum.setText(airplane.getAirplaneNum());
        txtAirplaneNum.setEnabled(false);
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        for(int i = 0; i < col.length; i++ )
            ComboBoxCol.addItem(Integer.toString(col[i]));           
       
        for(int i = 0; i < 3; i++)
            ComboBoxType.addItem(type[i]); 
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAirplaneNum = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCol = new javax.swing.JComboBox<>();
        ComboBoxType = new javax.swing.JComboBox<>();
        ComboBoxRowNum = new javax.swing.JComboBox<>();
        btnView = new javax.swing.JButton();

        btnBack1.setText("Back ->");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Customer Information");

        jLabel2.setText("Name");

        jLabel6.setText("Flight Number");

        txtAirplaneNum.setEnabled(false);

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnBack2.setText("Back ->");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose your seat");

        ComboBoxCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxColActionPerformed(evt);
            }
        });

        ComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTypeActionPerformed(evt);
            }
        });

        ComboBoxRowNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRowNumActionPerformed(evt);
            }
        });

        btnView.setText("View Available Seat");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirplaneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnView))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxRowNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(196, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAirplaneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(ComboBoxRowNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardSequenceForFlightJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceForFlightJPanel.getLayout();
        layout.previous(CardSequenceForFlightJPanel);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        CardSequenceForFlightJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceForFlightJPanel.getLayout();
        layout.previous(CardSequenceForFlightJPanel);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void ComboBoxColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxColActionPerformed
        // TODO add your handling code here       
    }//GEN-LAST:event_ComboBoxColActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:   
        String col  = ComboBoxCol.getSelectedItem().toString();
        String type  = ComboBoxType.getSelectedItem().toString();
        String rowNum  = ComboBoxRowNum.getSelectedItem().toString();
        
        if(txtName.getText() == null ||txtName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You should enter a name", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }  
        if(ComboBoxCol.getSelectedItem().toString()==null ||ComboBoxCol.getSelectedItem().toString().equals("") ){
            JOptionPane.showMessageDialog(null, "You should select a seat column", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if( ComboBoxType.getSelectedItem().toString()==null || ComboBoxType.getSelectedItem().toString().equals("") ){
            JOptionPane.showMessageDialog(null, "You should select a seat Type", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(ComboBoxRowNum.getSelectedItem().toString()==null ||ComboBoxRowNum.getSelectedItem().toString().equals("") ){
            JOptionPane.showMessageDialog(null, "You should select a seat row", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Customer customer = customerDirectory.addCustomer();
        customer.setAirplanePicked(airplane.getAirplaneNum());
        customer.setName(txtName.getText());
        customer.setSeatColumn(Integer.parseInt(col));
        customer.setSeatType(type);
        customer.setSeatRowNum(Integer.parseInt(rowNum));

        airplane.setSeatSelected(Integer.parseInt(col), type, Integer.parseInt(rowNum));

        ViewCustomerDiretoryJPanel panel = new ViewCustomerDiretoryJPanel(CardSequenceForFlightJPanel,customerDirectory);
        CardSequenceForFlightJPanel.add("CreateNewFlightJPanel", panel);
        CardLayout layout = (CardLayout) CardSequenceForFlightJPanel.getLayout();
        layout.next(CardSequenceForFlightJPanel);
    
   
    }//GEN-LAST:event_btnBookActionPerformed

    private void ComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTypeActionPerformed
        // TODO add your handling code here: 
    
    }//GEN-LAST:event_ComboBoxTypeActionPerformed

    private void ComboBoxRowNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRowNumActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxRowNumActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ComboBoxRowNum.removeAllItems();
        String c  = ComboBoxCol.getSelectedItem().toString();
        String t  = ComboBoxType.getSelectedItem().toString();

        int[] rowNum = airplane.getAvailableRowNum(Integer.parseInt(c), t);
        for(int i = 0; i< rowNum.length; i++){
            if(rowNum[i] != 0)
                ComboBoxRowNum.addItem(String.valueOf(rowNum[i]));
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCol;
    private javax.swing.JComboBox<String> ComboBoxRowNum;
    private javax.swing.JComboBox<String> ComboBoxType;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAirplaneNum;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
