/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners.ManageFlights;

import Business.Airplane;
import UserInterface.ManageAirliners.ManageFlights.BookCustomerReservation.ManageCustomerJPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Keyu Liu
 */
public class ViewFlightDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJPanel
     */
    private JPanel CardSequenceForFlightJPanel;
    private Airplane airplane;

    public ViewFlightDetailJPanel(JPanel CardSequenceForFlightJPanel, Airplane airplane ) {
        this.CardSequenceForFlightJPanel = CardSequenceForFlightJPanel;
        this.airplane = airplane;
        initComponents();
        populateAirplaneDetails();
    }
    private void populateAirplaneDetails(){
        txtFlightNum.setText(airplane.getAirplaneNum());  
        txtDepartureLocation.setText(airplane.getDepartureLocation());
        txtArrivalLocation.setText(airplane.getArrivalLocation()); 
        txtAvailableSeatsNum.setText(Integer.toString(airplane.getAvailableSeatsNum()));
        

        if(airplane.getPreferTime().equals("Morning")){
            radioBtnMorning.setSelected(true);
        }
        else if (airplane.getPreferTime().equals("Day time")){
            radioBtnDayTime.setSelected(true);
        }
        else if (airplane.getPreferTime().equals("Evening")) {
            radioBtnEvening.setSelected(true);
        }
        
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date arrivalDate = airplane.getArrivalDate();
        String arrivalDateString = formatter.format(arrivalDate);
        txtArrivalDate.setText(arrivalDateString);
        
        Date departureDate = airplane.getDepartureDate();
        String departureDateString = formatter.format(departureDate);
        txtDepartureDate.setText(departureDateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFlightNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDepartureLocation = new javax.swing.JTextField();
        txtArrivalLocation = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtArrivalDate = new javax.swing.JTextField();
        radioBtnMorning = new javax.swing.JRadioButton();
        radioBtnDayTime = new javax.swing.JRadioButton();
        radioBtnEvening = new javax.swing.JRadioButton();
        btnBook = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAvailableSeatsNum = new javax.swing.JTextField();
        txtDepartureDate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jPanel2.setPreferredSize(new java.awt.Dimension(700, 596));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("View Flight");

        jLabel8.setText("Flight number");

        txtFlightNum.setEnabled(false);

        jLabel9.setText("Preferred time of day");

        jLabel10.setText("Arrival locaiton");

        jLabel11.setText("Departure location");

        txtDepartureLocation.setEnabled(false);
        txtDepartureLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartureLocationActionPerformed(evt);
            }
        });

        txtArrivalLocation.setEnabled(false);

        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel12.setText("Arrival Date");

        txtArrivalDate.setEnabled(false);

        buttonGroup1.add(radioBtnMorning);
        radioBtnMorning.setText("Morning");
        radioBtnMorning.setEnabled(false);

        buttonGroup1.add(radioBtnDayTime);
        radioBtnDayTime.setText("Day time");
        radioBtnDayTime.setEnabled(false);

        buttonGroup1.add(radioBtnEvening);
        radioBtnEvening.setText("Evening");
        radioBtnEvening.setEnabled(false);

        btnBook.setText("Book customer reservation");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnBack.setText("Back ->");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Available seats number");

        txtAvailableSeatsNum.setEnabled(false);

        txtDepartureDate.setEnabled(false);

        jLabel13.setText("Departure Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArrivalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDepartureLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFlightNum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnMorning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnDayTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnEvening))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAvailableSeatsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 192, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFlightNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartureLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArrivalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnMorning)
                    .addComponent(radioBtnDayTime)
                    .addComponent(radioBtnEvening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvailableSeatsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBook, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepartureLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartureLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartureLocationActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        //Validation of prefer time
        Airplane airplane = this.airplane;   
        if(radioBtnMorning.isSelected()){       
            airplane.setPreferTime("Morning");       
        }
        else if(radioBtnDayTime.isSelected()){
            airplane.setPreferTime("Day time");       
        }
        else if(radioBtnEvening.isSelected()){
            airplane.setPreferTime("Evening");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a prefered time of day for this airplane!", "Warning",JOptionPane.WARNING_MESSAGE); 
        }
        
        //Get user's input
        String airplaneNum = txtFlightNum.getText();
        String departureLocation = txtDepartureLocation.getText();
        String arrivalLocation = txtArrivalLocation.getText();
        String arrivalDate = txtArrivalDate.getText();  
        String departureDate = txtDepartureDate.getText();
        
        //Validation of airplane number
        if (airplaneNum == null || airplaneNum.equals("")){
            JOptionPane.showMessageDialog(null, "You should enter at least one airplane number for this plane", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }  
        
        //Validation of departure location and arrival location
        if (departureLocation  == null || departureLocation .equals("")){
            JOptionPane.showMessageDialog(null, "departureLocation  can't be empty!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (arrivalLocation == null || arrivalLocation.equals("")){
            JOptionPane.showMessageDialog(null, "arrivalLocation can't be empty!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(arrivalLocation.equals(departureLocation)){
            JOptionPane.showMessageDialog(null, "Arrival location can't same as departure location!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        airplane.setAirplaneNum(airplaneNum);
        airplane.setDepartureLocation(departureLocation );
        airplane.setArrivalLocation(arrivalLocation);
        airplane.setArrivalDate(arrivalDate);
        airplane.setDepartureDate(departureDate);
        
        //validation of arrival arrivalDate and departure arrivalDate
        if(airplane.isDateUnnormal()){
           JOptionPane.showMessageDialog(null, "Flight arrival time cannot ealier than departure time!!", "Warning", JOptionPane.WARNING_MESSAGE);
           return;
        }

        JOptionPane.showMessageDialog(null, "Car data successfully created!");

        txtFlightNum.setText("");
        txtDepartureLocation.setText("");
        txtArrivalLocation.setText("");
        txtArrivalDate.setText("");
        txtDepartureDate.setText("");
        radioBtnMorning.setSelected(false);
        radioBtnDayTime.setSelected(false);
        radioBtnEvening.setSelected(false);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFlightNum.setEnabled(true);
        txtDepartureLocation.setEnabled(true);
        txtArrivalLocation.setEnabled(true);
        txtArrivalDate.setEnabled(true);
        txtDepartureDate.setEnabled(true);
        radioBtnMorning.setEnabled(true);
        radioBtnDayTime.setEnabled(true);
        radioBtnEvening.setEnabled(true);
        btnConfirm.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        
        ManageCustomerJPanel panel = new ManageCustomerJPanel(CardSequenceForFlightJPanel, airplane);
        CardSequenceForFlightJPanel.add("ManageCustomerJPanel", panel);
        CardLayout layout = (CardLayout) CardSequenceForFlightJPanel.getLayout();
        layout.next(CardSequenceForFlightJPanel);
        
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceForFlightJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceForFlightJPanel.getLayout();
        layout.previous(CardSequenceForFlightJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioBtnDayTime;
    private javax.swing.JRadioButton radioBtnEvening;
    private javax.swing.JRadioButton radioBtnMorning;
    private javax.swing.JTextField txtArrivalDate;
    private javax.swing.JTextField txtArrivalLocation;
    private javax.swing.JTextField txtAvailableSeatsNum;
    private javax.swing.JTextField txtDepartureDate;
    private javax.swing.JTextField txtDepartureLocation;
    private javax.swing.JTextField txtFlightNum;
    // End of variables declaration//GEN-END:variables
}
