/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Search;

import Business.Airplane;
import UserInterface.ManageAirliners.ManageFlights.ViewFlightDetailJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siyuan Zhang
 */
public class FlightsFoundJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private ArrayList<Airplane> searchResult;
    
    /**
     * Creates new form FlightsFoundJPanel
     */
    public FlightsFoundJPanel(JPanel userProcessContainer, ArrayList<Airplane> searchResult) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.searchResult = searchResult;
        populateTable();
    }
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblAirplanes.getModel();
        dtm.setRowCount(0);
        
        for(Airplane airplane: this.searchResult){
            Object[] row = new Object[6];
            row[0] = airplane;
            row[1] = airplane.getDepartureLocation();
            row[2] = airplane.getArrivalLocation();
            row[3] = airplane.getPreferTime();
            row[4] = airplane.getArrivalDate();
            row[5] = airplane.getDepartureDate();
            dtm.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplanes = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewFlightDetail = new javax.swing.JButton();

        tblAirplanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Number", "Departure Location", "Arrival Location", "Preferred Time", "Arrival Date", "Departure Date"
            }
        ));
        jScrollPane1.setViewportView(tblAirplanes);

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewFlightDetail.setText("View flight detail");
        btnViewFlightDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewFlightDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnViewFlightDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewFlightDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightDetailActionPerformed
        
        int selectedRow = tblAirplanes.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "To view the detail please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Airplane airplane = (Airplane)tblAirplanes.getValueAt(selectedRow, 0);
            
            ViewFlightDetailJPanel panel = new ViewFlightDetailJPanel(userProcessContainer, airplane);
            userProcessContainer.add("ViewFlightDetailJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnViewFlightDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewFlightDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirplanes;
    // End of variables declaration//GEN-END:variables
}
